name: code review

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    # 19:00(UTC) 每天，相当于 03:00(GMT+8)
    - cron: '0 19 * * *'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-npm
      - uses: biomejs/setup-biome@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: biome ci .

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-npm
      - run: pnpm run test:coverage
      - uses: codacy/codacy-coverage-reporter-action@v1
        if: github.actor != 'dependabot[bot]'
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
          coverage-reports: coverage/lcov.info
