name: code review

on:
  push:
    branches:
      - v*.x
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-npm
      - uses: biomejs/setup-biome@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm run lint
